name: NestJS CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22'
    
    - name: Install Dependencies
      run: npm install
    
    - name: Build Project
      run: npm run build

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
    
    - name: Install Dependencies
      run: npm install
    
    - name: Build Project
      run: npm run build
    
    - name: Deploy to Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        
        script: |
          bash -c '
            export PATH=$PATH:/root/.nvm/versions/node/v22.12.0/bin/
            cd /home/project/test-nest-snapp/SnappFood-Nestjs
            git pull
            npm install
            npm run build
            pm2 restart nest-snappfood || pm2 start npm --name "nest-snappfood" -- run start
          '
