name: CI/CD for NestJS Project- snappfood

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build

      - name: Deploy to Server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          ssh-add - <<< "$SSH_PRIVATE_KEY"
          ssh -o StrictHostKeyChecking=no root@65.109.187.30 << 'EOF'
            cd /home/project/test-nest-snapp/SnappFood-Nestjs
            git pull
            npm install
            npm run build
            npm run start:dev
          EOF
